#month, day, comments
weekly_misc = [[8,25,"	 Student Late Start Wednesday"],
[9,1," No Student Late Start; Monday off"],
[9,8,"	 Student Late Start Wednesday; 9th Grade Retreat Wednesday - Friday"],
[9,15,"7th Grade Retreat Wednesday - Friday. Student Late Start Wednesday"],
[9,22," No School Tuesday, Rosh Hashanah, Special Schedule Monday (Big Windward Read)"],
[9,29," No School Thursday, Yom Kippur, Back to School Night Tuesday, No Student Late Start	"],
[10,6," Student Late Start Wednesday"],
[10,13,"	 Student Late Start Wednesday Special Schedule Wednesday - Prospective Student Open House"],
[10,20,"  No school Monday. No Student Late Start Wednesday"],
[10,27,"	 Student Late Start Wednesday"],
[11,3,"End of grading period on Thurs.; No Student Late Start, Faculty Inservice on Friday (no classes)"],
[11,10,"  Late Start Wed.; Special Schedule Tuesday - Prospective Student Open House"],
[11,17," Junior College Trip (11. 17 - 22) Late Start Wed."],
[12,1,"	 Student Late Start Wed."],
[12,8," Special Schedule Wed. and Thurs. - Parent/Guardian Conferences"],
[12,15," Special Schedule Friday (Alumni Lunch); Special Schedule Tues. and Wed. Parent/Guardian Conferences"],
[1,5,"	 Student Late Start Wednesday."],
[1,12,"  No Student Late Start - Inservice Friday"],
[1,19,"  No Student Late Start"],
[1,26,"	 Special Schedule Friday (Founders’ Day) - Student Late Start Wed."],
[2,2,"	  Student Late Start Wednesday"],
[2,9,"	 Student Late Start Wednesday	"],
[2,23,"	 Student Late Start Wednesday"],
[3,2," End of Grading Period Friday - Late Start Wednesday"],
[3,9,"	 Student Late Start Wednesday; "],
[3,16,"	 Student Late Start Wednesday; "],
[4,6,"	 Student Late Start Wednesday"],
[4,13,"  Student Late Start Wednesday; 8th Grade Minimester Trips, Tuesday - Friday"],
[4,20,"	 Student Late Start Wednesday"],
[4,27,"  Student Late Start Wednesday"],
[5,4,"	  AP’s - Student Late Start Wednesday"],
[5,11,"	 AP’s - Student Late Start Wednesday"],
[5,18,"	 Student Late Start Wed."],
[5,25," Graduation on Thursday, no classes Monday (Memorial Day) and Thursday (Graduation), Days 3 and 4 (WL Written and History Assessments only), Day 5 (WL Oral and English Assessments Only)"],
[6,1,"	 on Monday (WL Oral and English Assessments Only), "]]